name: Update README

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu_lastest
    name: Update Profile README

    steps:
      - uses: action/checkout@2.3.4

      - uses: Readme-Workflows/recent-activity@2.4.1
        env:
          GITHUB_TOKEN ${{ secrets.Github_TOKEN }}
